Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\order.py", line 639, in GET
    role = web.ctx.session.session_role;
  File "C:\Python27\lib\site-packages\web\session.py", line 71, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_role'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\order.py", line 639, in GET
    role = web.ctx.session.session_role;
  File "C:\Python27\lib\site-packages\web\session.py", line 71, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_role'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\order.py", line 639, in GET
    role = web.ctx.session.session_role;
  File "C:\Python27\lib\site-packages\web\session.py", line 71, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_role'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 250, in GET
    return render.thirdeval(orderid = orderid,queryDict = query_dict)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 135, in render_body
  File "componentsThirdEval_html", line 108, in render_layoutControlList
  File "C:\Python27\lib\site-packages\configobj.py", line 661, in pop
    val = self[key]
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'thirdeval_class'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 250, in GET
    return render.thirdeval(orderid = orderid,queryDict = query_dict)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 142, in render_body
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'InsurantUsr'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 250, in GET
    return render.thirdeval(orderid = orderid,queryDict = query_dict)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 142, in render_body
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'InsurantUsr'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 209, in zipOrderInfoOrder
    configPageUsing = configPage['PolicyHolder_Usr']
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'PolicyHolder_Usr'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 416, in postThirdEvalInfo
    c.perform()
error: (7, 'Failed to connect to localhost port 80: Connection refused')
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 212, in POST
    return render.order(orderid = orderidStr)
  File "C:\Python27\lib\site-packages\web\contrib\template.py", line 113, in __getattr__
    t = self._lookup.get_template(path)
  File "C:\Python27\lib\site-packages\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\Python27\lib\site-packages\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\Python27\lib\site-packages\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Python27\lib\site-packages\mako\template.py", line 416, in _compile_from_file
    filename)
  File "C:\Python27\lib\site-packages\mako\template.py", line 714, in _compile_text
    exec(code, module.__dict__, module.__dict__)
  File "order_html", line 16, in <module>
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\OrderClient.py", line 60
SyntaxError: Non-ASCII character '\xe5' in file C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\OrderClient.py on line 60, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 212, in POST
    return render.thirdeval(orderid = orderidStr)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 68, in render_body
AttributeError: 'Undefined' object has no attribute 'getThirdEvalInfo'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 212, in POST
    return render.thirdeval(orderid = orderidStr)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 68, in render_body
AttributeError: 'Undefined' object has no attribute 'getThirdEvalInfo'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 212, in POST
    return render.thirdeval(orderid = orderidStr)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 66, in render_body
AttributeError: 'Undefined' object has no attribute 'getThirdEvalInfo'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 60, in GET
    return render.thirdevalList(orderid=orderid,pageindex=pageindex)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdevalList_html", line 108, in render_body
  File "thirdevalList_html", line 42, in layoutdata
  File "thirdevalList_html", line 160, in render_layoutdata
KeyError: 'OrderId'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 60, in GET
    return render.thirdevalList(orderid=orderid,pageindex=pageindex)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdevalList_html", line 113, in render_body
KeyError: 'PageManager'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 60, in GET
    return render.thirdevalList(orderid=orderid,pageindex=pageindex)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdevalList_html", line 119, in render_body
KeyError: 'PageSize'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 60, in GET
    return render.thirdevalList(orderid=orderid,pageindex=pageindex)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdevalList_html", line 131, in render_body
TypeError: 'Undefined' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 85, in POST
    retStr = ThirdEvalDomainHandler.postThirdEvalInfo(data)
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 301, in postThirdEvalInfo
    localData =  dbSqlite.select('thirdeval_detail')
  File "C:\Python27\lib\site-packages\web\db.py", line 699, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 1042, in query
    out = DB.query(self, *a, **kw)
  File "C:\Python27\lib\site-packages\web\db.py", line 659, in query
    self._db_execute(db_cursor, sql_query)
  File "C:\Python27\lib\site-packages\web\db.py", line 591, in _db_execute
    out = cur.execute(query, params)
OperationalError: no such table: thirdeval_detail
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 85, in POST
    retStr = ThirdEvalDomainHandler.postThirdEvalInfo(data)
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 301, in postThirdEvalInfo
    localData =  dbSqlite.select('thirdeval_detail')
  File "C:\Python27\lib\site-packages\web\db.py", line 699, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 1042, in query
    out = DB.query(self, *a, **kw)
  File "C:\Python27\lib\site-packages\web\db.py", line 659, in query
    self._db_execute(db_cursor, sql_query)
  File "C:\Python27\lib\site-packages\web\db.py", line 591, in _db_execute
    out = cur.execute(query, params)
OperationalError: no such table: thirdeval_detail
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 85, in POST
    retStr = ThirdEvalDomainHandler.postThirdEvalInfo(data)
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 301, in postThirdEvalInfo
    localData =  dbSqlite.select("thirdeval_detail")
  File "C:\Python27\lib\site-packages\web\db.py", line 699, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 1042, in query
    out = DB.query(self, *a, **kw)
  File "C:\Python27\lib\site-packages\web\db.py", line 659, in query
    self._db_execute(db_cursor, sql_query)
  File "C:\Python27\lib\site-packages\web\db.py", line 591, in _db_execute
    out = cur.execute(query, params)
OperationalError: no such table: thirdeval_detail
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 85, in POST
    retStr = ThirdEvalDomainHandler.postThirdEvalInfo(data)
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 301, in postThirdEvalInfo
    localData =  dbSqlite.select("thirdeval_detail")
  File "C:\Python27\lib\site-packages\web\db.py", line 699, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 1042, in query
    out = DB.query(self, *a, **kw)
  File "C:\Python27\lib\site-packages\web\db.py", line 659, in query
    self._db_execute(db_cursor, sql_query)
  File "C:\Python27\lib\site-packages\web\db.py", line 591, in _db_execute
    out = cur.execute(query, params)
OperationalError: no such table: thirdeval_detail
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 85, in POST
    retStr = ThirdEvalDomainHandler.postThirdEvalInfo(data)
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 306, in postThirdEvalInfo
    orderid = item['orderid']
KeyError: 'orderid'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 132, in GET
    return render.thirdeval(orderid = orderid,queryDict = query_dict)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdeval_html", line 111, in render_body
  File "componentsThirdEval_html", line 108, in render_layoutControlList
  File "C:\Python27\lib\site-packages\configobj.py", line 661, in pop
    val = self[key]
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'sex'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 60, in flatThirdEvalInfo
    addDictItemValue(item,'BASIC_NAME',localThirdEvalInfo,configPageUsing['basic_name']['dataName'])
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'basic_name'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 75, in flatThirdEvalInfo
    addDictItemValue(item,"LEER_SPIRIT_DEPRESS",localThirdEvalInfo,configPageUsing['leer_spirit_depress"']['dataName'])
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'leer_spirit_depress"'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 75, in flatThirdEvalInfo
    addDictItemValue(item,"LEER_SPIRIT_DEPRESS",localThirdEvalInfo,configPageUsing['spirit_depress"']['dataName'])
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'spirit_depress"'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 75, in flatThirdEvalInfo
    addDictItemValue(item,"LEER_SPIRIT_DEPRESS",localThirdEvalInfo,configPageUsing['spirit_depress"']['dataName'])
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'spirit_depress"'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalDomainHandler.py", line 75, in flatThirdEvalInfo
    addDictItemValue(item,"LEER_SPIRIT_DEPRESS",localThirdEvalInfo,configPageUsing['spirit_depress"']['dataName'])
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'spirit_depress"'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalClient.py", line 60, in getThirdEvalInfo
    if localOrderInfo is not None:
UnboundLocalError: local variable 'localOrderInfo' referenced before assignment
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\thirdeval.py", line 60, in GET
    return render.thirdevalList(orderid=orderid,pageindex=pageindex)
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "thirdevalList_html", line 115, in render_body
  File "thirdevalList_html", line 42, in layoutdata
  File "thirdevalList_html", line 166, in render_layoutdata
  File "thirdevalList_html", line 99, in body
KeyError: 'id'
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalClient.py", line 60, in getThirdEvalInfo
    if localOrderInfo is not None:
UnboundLocalError: local variable 'localOrderInfo' referenced before assignment
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalClient.py", line 60, in getThirdEvalInfo
    if localOrderInfo is not None:
UnboundLocalError: local variable 'localOrderInfo' referenced before assignment
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalClient.py", line 60, in getThirdEvalInfo
    if localOrderInfo is not None:
UnboundLocalError: local variable 'localOrderInfo' referenced before assignment
Traceback (most recent call last):
  File "C:/Users/stone/OneDrive/Stone/Python_local/Python_Insurance\ThirdEvalClient.py", line 60, in getThirdEvalInfo
    if localOrderInfo is not None:
UnboundLocalError: local variable 'localOrderInfo' referenced before assignment
